### ISSUE TITLE
Equate Symbol Storage

### ISSUE THREAD

**Issue by shizhongpwn** [StarCrossPortal/bincraft#16]
When you set a new equate to a number appear in Listing area but not be identified to a variable in deompile area, and then if you want to rename a variable in decompile area, you will get a error message. 

And I have found the reason, ghidra will storage all equate symbols in symbol table and produce their hash storage in LocalSymbolMap, so when you rename a variable, ghidra will search for the LocalSymbolMap and make you operate failed.

**Comment by Escapingbug** [comment]
In my opinion, we should not let users "rename" an `EquateSymbol` in decompiler panel. Maybe you should try remove that renaming and retyping functionality.
